apiVersion: batch/v1
kind: Job
metadata:
  name: cve-news-search
spec:
  template:
    metadata:
      labels:
        app: "cve-news-search"
    spec:
      containers:
        - name: "cve-news-search"
          image: "akoderman/cve-news-search:latest"
          resources:
            requests:
              memory: "20Mi"
            limits:
              memory: "300Mi"
          env:
          - name: PYTHONDONTWRITEBYTECODE
            value: "1"
          workingDir: /cve-news-search
          command: ["scripts/init.sh"]
      restartPolicy: Never
      volumes:
        - name: "cve-news-search-conf"
          configMap:
            name: "cve-news-search-configmap"


